/**
 * Agent session, event, component, and store state types.
 */

import type { AgentStatus, WorkflowStatus } from '../utils/status';
import type { LlmRegistrySnapshot, ModelParameterSchema, ModelSpec } from './llm';
import type { Tool, McpHostStatus, McpClientStatus } from './tools';
import type { Workflow } from './workflow';

// Saved agent record as returned by the REST API
export interface SavedAgent {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  avatarImage: string | null;
  color: string | null;
  agentConfig: AgentConfig;
  isPublic: boolean;
  createdAt: string;
  updatedAt: string;
}

// Wire format for agents in events (no metadata, just config)
// This is the core agent identity: ID + execution config.
export interface Agent {
  agentId: string;        // 'none' (assistant) or saved agent UUID
  config: AgentConfig;
}

// Agent configuration (per-call settings)
export interface AgentConfig {
  modelId: string;
  providerId?: string;
  // Client-authored operating directives (UI label: "System Instructions").
  clientInstructions?: string;
  stream: boolean;
  maxModelCalls: number;

  // harness owned configuration
  enableTools: boolean;
  availableTools: Tool[];
  maxConcurrentTools: number;

  // OpenRouter/OpenAI-compatible request parameters using native snake_case keys.
  providerParameters: Record<string, unknown>;
}

// Base interface for all native tool metadata
export interface BaseNativeToolMetadata {
  tool: string;
  callsCount: number;
}

// Generic native tool metadata (Provider-agnostic)
export interface NativeToolMetadata extends BaseNativeToolMetadata {
  provider?: string;
  data?: Record<string, unknown>; // Flexible bag for specific metadata
  [key: string]: unknown;         // Allow extensions
}

// Metadata for MCP tools
export interface McpToolMetadata {
  tool: string;
  server: string;
  callsCount: number;
  totalExecutionTime: number;
}

// Normalized usage metrics (all models should output this format)
export interface UsageMetrics {
  inputTokens?: number;
  outputTokens?: number;
  totalTokens?: number;
  thinkingTokens?: number;
  cacheReadTokens?: number;
  cacheCreationTokens?: number;
  maxTokens?: number;  // Model's max context window (from model spec)
}

// Agent metadata
export interface AgentMetadata {
  usage?: UsageMetrics;
  nativeTools?: NativeToolMetadata[];
  mcpTools?: McpToolMetadata[];
  modelCallsCount?: number;

  // Per-call metrics (tracked by models.ts)
  modelCallDuration?: number;        // Total API call duration

  // Turn-scoped aggregated metrics
  totalModelCallDuration?: number;
  totalToolsExecutionDuration?: number;
  agentTurnDuration?: number;        // Running turn duration (updated on each event)

  // Tool-specific metrics (in tool-result events)
  toolExecutionDuration?: number;    // Single tool execution time
}

// Feedback action button configuration
export interface FeedbackAction {
  id: string;                   // Action identifier (e.g., 'approve', 'cancel')
  label: string;                // Button text
  variant?: 'default' | 'outline' | 'destructive' | 'secondary' | 'ghost';

  // Icon configuration
  icon?: string;                // Lucide icon name (e.g., 'Check', 'X', 'ThumbsUp')
  iconPosition?: 'left' | 'right';

  // Additional metadata
  description?: string;         // Tooltip or subtitle text
  shortcut?: string;            // Keyboard shortcut hint (e.g., 'Enter', 'Esc')

  // Visual emphasis
  primary?: boolean;            // Highlight as primary action
  dangerous?: boolean;          // Show warning state

  data?: unknown;                   // Optional data to include in response
}

// Session metadata (persistent identity)
export interface SessionMetadata {
  sessionId?: string;
  title?: string;
  titleLocked?: boolean;
  agentName: string;
  rootSessionId?: string;  // NULL for roots, points to root for branches
  workflow?: string;  // Workflow id used for this session
}

// Tool effects (applied after tool execution)
// Tools can return effects to be processed by Session or UI
// Each key is an effect type, value is the effect data
export interface ToolEffects {
  // UI-handled effects
  updateConfig?: Partial<AgentConfig>;
  sessionComponents?: (Omit<SessionComponent, 'data'> & { data: SessionComponent['data'] })[];
  userActions?: {
    prompt: string;
    actions: FeedbackAction[];
  };
  // Backend-owned: session tool-state writes, projected server-side and
  // surfaced to the model only via system-call tools. The UI does not act on
  // these.
  stateUpdates?: Array<{ key: string; value: unknown }>;
}

// Tool result event data (generated by agent-session.ts)
export interface ToolResultData {
  server: string;
  tool: string;
  arguments?: Record<string, unknown>;
  result: unknown;
  metadata: AgentMetadata;
}

// Tool effects event data (effects produced by tool execution)
export interface ToolEffectsData {
  server: string;
  tool: string;
  toolEffects: ToolEffects;     // Effects to apply (session + UI)
  metadata: AgentMetadata;
}

// Tool call event data (generated by call-model.ts)
export interface ToolCallData {
  server: string;
  tool: string;
  arguments?: Record<string, unknown>;
  metadata: AgentMetadata;
  thoughtSignature?: string;    // Gemini 3+ thinking signature (must be sent back)
}

// Granular event data types (generated by call-model.ts)
export interface ThoughtChunkData {
  thoughts: string;  // Incremental thought text
  metadata: AgentMetadata;  // Accumulated metadata at chunk time
}

export interface ThoughtCompletedData {
  thoughts: string;             // Complete accumulated thoughts
  metadata: AgentMetadata;
}

export interface MessageChunkData {
  message: string;  // Incremental message text
  metadata: AgentMetadata;  // Accumulated metadata at chunk time
}

export interface MessageCompletedData {
  message: string;              // Complete accumulated message
  metadata: AgentMetadata;
  libraryItemIds?: string[];    // Generated image asset IDs (for image generation models)
}

// User turn completion (generated by session.ts after building user turn)
export interface UserInputCommittedData {
  message?: string;             // User message text
  agents: Agent[];              // Ordered agent configs for this turn ([0] = active)
  metadata: AgentMetadata;
  libraryItemIds?: string[];    // Library item IDs (assets or folders) attached to this turn
  encodedImages?: Array<{ mimeType: string; data: string }>;  // Base64 images attached to this turn
}

// Agent turn completion (generated by session.ts after orchestration)
export interface AgentTurnCompletedData {
  metadata: AgentMetadata;            // Execution metadata (usage, grounding, etc.)
}

// Branch event data (generated when creating a new session branch)
// In parent session: branchSessionId points to child
// In branch session: parentSessionId points to parent
export interface SessionBranchedEventData {
  parentSessionId?: string;     // Parent session (only in branch session)
  branchSessionId?: string;     // Child session (only in parent session)
  metadata: AgentMetadata;
}

// User feedback result event data (generated when user provides feedback)
// Links to tool-call via toolCallEventId (same as tool-call.eventId)
export interface UserFeedbackResultData {
  server: string;                                   // Tool server (e.g., 'system-call')
  tool: string;                                     // Tool name (e.g., 'update_state')
  arguments: Record<string, unknown>;                                   // Original tool arguments for display
  result: unknown;                  // User's feedback data (action, text, etc.)
  metadata: AgentMetadata;
}

// Session component types
export type SessionComponentType =
  | 'message'
  | 'user-message'
  | 'agent-message'
  | 'agent-thoughts'
  | 'tool-result'
  | 'tool-call'
  | 'system-call'
  | 'user-feedback'
  // system components
  | 'config-panel'
  | 'history-panel'
  | 'settings-panel'
  | 'asset-picker-panel'
  | 'resume-workflow';

// Session component controls (explicit button visibility)
export interface SessionComponentControls {
  debug?: boolean;      // Show debug/events panel button
  edit?: boolean;       // Show edit button
  revert?: boolean;     // Show revert/branch button
  branch?: boolean;     // Show branch navigation
  translate?: boolean;  // Show translate button (message components only)
}

// Session component data — all fields explicitly declared.
// Standard fields come from event.data spreads in the mapper.
// Tool-owned fields (job, proposal, etc.) come from toolEffects.sessionComponents.
export interface SessionComponentData {
  // Text content (streaming append or completion replace)
  message?: string;
  thoughts?: string;

  // Event metadata
  metadata?: AgentMetadata;
  interactionId?: string;
  agentId?: string;

  // Tool identity
  server?: string;
  tool?: string;
  arguments?: Record<string, unknown>;
  result?: unknown;
  error?: string;
  isError?: boolean;

  // Event history (append-only, deduplicated by eventId)
  sessionEvents?: SessionEvent[];

  // User turn data (spread from UserInputCommittedData)
  agents?: Agent[];
  libraryItemIds?: string[];
  encodedImages?: Array<{ mimeType: string; data: string }>;

  // Tool call data (spread from ToolCallData)
  thoughtSignature?: string;

  // Tool effects data (spread from ToolEffectsData)
  toolEffects?: ToolEffects;

  // Composite data (agent-message type in chat mode)
  items?: SessionComponent[];
  hasResponse?: boolean;
}

// Session component (UI display)
export interface SessionComponent {
  id: string;
  role: 'user' | 'agent' | 'system';
  type: SessionComponentType;
  isStreaming?: boolean;      // True for chunk events, false/undefined otherwise
  hideComponent?: boolean;    // UI visibility: hide from foreground chat
  controls?: SessionComponentControls;  // Explicit button visibility
  data: SessionComponentData;
}

// UI interface mode — determines component derivation strategy
export type UIInterface = 'chat' | 'flat';

// Session event base fields
interface SessionEventBase {
  eventId: string;              // Unique per event
  workflowId: string | null;    // Run-scoped events stamp the active workflow id
  runId: string | null;         // Run-scoped events stamp the active run id
  interactionId: string;        // Interaction id — shared between user-input-committed and all events produced by the run it kicked off
  agentId?: string;             // Which agent produced this event ('none' = assistant, UUID = saved agent)
  toolCallEventId?: string;     // Links tool-result/tool-effects/user-feedback-result to originating tool-call's eventId
  role: 'user' | 'agent' | 'system'; // Event owner role
  sequence: number;
  timestamp: Date;              // When event was created
}

// Individual typed event interfaces
export interface ModelThoughtChunkEvent extends SessionEventBase {
  type: 'model-thought-chunk';
  data: ThoughtChunkData;
}

export interface ModelThoughtCompletedEvent extends SessionEventBase {
  type: 'model-thought-completed';
  data: ThoughtCompletedData;
}

export interface ModelMessageChunkEvent extends SessionEventBase {
  type: 'model-message-chunk';
  data: MessageChunkData;
}

export interface ModelMessageCompletedEvent extends SessionEventBase {
  type: 'model-message-completed';
  data: MessageCompletedData;
}

export interface ToolCallEvent extends SessionEventBase {
  type: 'tool-call';
  data: ToolCallData;
}

export interface ToolEffectsEvent extends SessionEventBase {
  type: 'tool-effects';
  data: ToolEffectsData;
}

export interface ToolResultEvent extends SessionEventBase {
  type: 'tool-result';
  data: ToolResultData;
}

export interface AgentTurnCompletedEvent extends SessionEventBase {
  type: 'agent-turn-completed';
  data: AgentTurnCompletedData;
}

export interface UserFeedbackResultEvent extends SessionEventBase {
  type: 'user-feedback-result';
  data: UserFeedbackResultData;
}

export interface UserInputCommittedEvent extends SessionEventBase {
  type: 'user-input-committed';
  data: UserInputCommittedData;
}

export interface SessionBranchedEvent extends SessionEventBase {
  type: 'session_branched';
  breakpointEventId?: string;   // Links branch to the event it was created from
  data: SessionBranchedEventData;
}

// ── Workflow run lifecycle events ──────────────────────────
// Emitted by the backend's WorkflowRuntime on every run. These are
// system-scoped (no agentId) and drive the WorkflowStatus state
// machine on the FE.

export interface WorkflowLifecycleData {
  workflowId: string;
  runId: string;
  origin?: { kind: string; connectionId?: string };
}

export interface WorkflowStartedEvent extends SessionEventBase {
  type: 'workflow_started';
  data: WorkflowLifecycleData;
}

export interface WorkflowResumedEvent extends SessionEventBase {
  type: 'workflow_resumed';
  data: WorkflowLifecycleData;
}

export interface WorkflowPausedEvent extends SessionEventBase {
  type: 'workflow_paused';
  data: WorkflowLifecycleData;
}

export interface WorkflowCompletedEvent extends SessionEventBase {
  type: 'workflow_completed';
  data: WorkflowLifecycleData;
}

export interface WorkflowAbortedEvent extends SessionEventBase {
  type: 'workflow_aborted';
  data: WorkflowLifecycleData;
}

export interface WorkflowFailedEvent extends SessionEventBase {
  type: 'workflow_failed';
  data: WorkflowLifecycleData & { error?: { code: string; message: string } };
}

export type WorkflowLifecycleEvent =
  | WorkflowStartedEvent
  | WorkflowResumedEvent
  | WorkflowPausedEvent
  | WorkflowCompletedEvent
  | WorkflowAbortedEvent
  | WorkflowFailedEvent;

// Union of all event types
export type SessionEvent =
  | ModelThoughtChunkEvent
  | ModelThoughtCompletedEvent
  | ModelMessageChunkEvent
  | ModelMessageCompletedEvent
  | ToolCallEvent
  | ToolEffectsEvent
  | ToolResultEvent
  | AgentTurnCompletedEvent
  | UserFeedbackResultEvent
  | UserInputCommittedEvent
  | SessionBranchedEvent
  | WorkflowLifecycleEvent;

// Editing state types
export type EditingData = {
  message?: string;
  arguments?: Record<string, unknown> | string; // String for JSON editing, parsed on submit
  result?: unknown; // For editing tool-call results
};

export interface EditableComponentData {
  eventId: string;
  type: 'user-message' | 'agent-message' | 'tool-call';
  fields: {
    message?: string;
    tool?: string;
    arguments?: Record<string, unknown>;
  };
}

export interface BranchRequest {
  parentSessionId: string;
  breakpointEventId: string;    // Event that triggers the branch
  modifiedData?: {              // If provided, creates edit branch; otherwise revert branch
    message?: string;
    tool?: string;
    arguments?: Record<string, unknown>;
  };
}

export interface BranchResponse {
  newSessionId: string;
  events: SessionEvent[];
  metadata: SessionMetadata;
}

// Default session metadata factory
export function createDefaultSessionMetadata(): SessionMetadata {
  return {
    agentName: 'assistant',
  };
}

// Agent Store State
export interface AgentState {
  // Current session
  currentSessionId: string | null;

  // Multi-agent: ordered list, [0] = front/active agent
  agents: Agent[];

  // Acquired agents library (owned + explicitly acquired), keyed by agent ID
  acquiredAgents: Record<string, SavedAgent>;

  // Internal state (prevents re-showing config panel on route changes)
  _hasShownInitialConfig: boolean;

  // Hydration state
  _hydrated: boolean;

  // User mode for message composition (timeline workflow)
  userMode: 'developer' | 'client';
  // Staged developer-authored message (Insert action — pending submit)
  stagedDeveloperMessage: string | null;

  // UI state
  uiInterface: UIInterface;
  sessionComponents: SessionComponent[];
  sessionEvents: SessionEvent[];
  activePanels: Map<string, SessionComponentType>;
  persistSession: boolean;
  ephemeral: boolean;
  userMessagesHistory: string[];  // Last N user messages for input navigation (most recent first)

  // Tool state
  toolsPool: Tool[];
  workflowsPool: Workflow[];
  modelsPool: ModelSpec[];
  modelParameters: ModelParameterSchema[];
  defaultModelId: string | null;

  rejectedTools: { server: string; tool: string; code: string }[];
  mcpHostStatus: McpHostStatus;
  mcpClientStatus: McpClientStatus;
  setMcpStatus: (hostStatus: McpHostStatus, clientStatus: McpClientStatus) => void;
  setRejectedTools: (rejectedTools: { server: string; tool: string; code: string }[]) => void;

  // Active session workflow selection (persisted in localStorage)
  selectedWorkflowId: string;

  // Scroll state
  scrollToComponentId: string | null;
  preserveScrollOnSessionChange: boolean;
  error: string | null;
  submitTrigger: number;

  // Editing state
  editingEventId: string | null;
  editingData: EditingData | null;

  // Branching state
  showingBranchesForComponent: string | null;

  // Translation state
  preferredTranslationLanguage: string | null;
  translationCache: Record<string, Record<string, string>>;
  activeTranslations: Record<string, string | null>;
  translatingComponents: Set<string>;

  // Pending library items (asset or folder IDs) for message attachment
  pendingLibraryItemIds: string[];

  // Per-agent runtime status (keyed by agentId). Ephemeral — never persisted.
  // Consumers that need an aggregate should use helpers from utils/status.
  agentStatuses: Record<string, AgentStatus>;

  // Active workflow run status (session-scoped). Source of truth lives in
  // the workflow_* system events on the session_event stream; this field
  // is the materialised view drained off `appendEvent`.
  workflowStatus: WorkflowStatus;
  workflowRunId: string | null;

  // Session management
  setCurrentSessionId: (sessionId: string | null) => void;

  // Multi-agent management
  setAgents: (agents: Agent[]) => void;
  addAgent: (agentId: string, config: AgentConfig) => void;
  removeAgent: (agentId: string) => void;
  toggleAgent: (agentId: string, config: AgentConfig) => void;
  updateFrontAgentConfig: (config: AgentConfig | ((prev: AgentConfig) => AgentConfig)) => void;
  setFrontAgent: (agentId: string) => void;  // Move agent to [0]

  // Acquired agents management
  setAcquiredAgents: (agents: SavedAgent[]) => void;
  getAcquiredAgent: (id: string) => SavedAgent | undefined;

  /** @deprecated Use agents[0].config / updateFrontAgentConfig instead */
  setAgentConfig: (config: AgentConfig | null | ((prev: AgentConfig | null) => AgentConfig | null)) => void;

  // Tool management
  setToolsPool: (tools: Tool[]) => void;
  setWorkflowsPool: (workflows: Workflow[]) => void;
  setSelectedWorkflowId: (id: string) => void;
  setLlmRegistry: (registry: LlmRegistrySnapshot) => void;

  // UI component actions
  setSessionComponents: (components: SessionComponent[] | ((prev: SessionComponent[]) => SessionComponent[])) => void;
  appendEvent: (event: SessionEvent) => void;
  hydrateFromEvents: (events: SessionEvent[]) => void;
  clearEvents: () => void;
  markInitialConfigShown: () => void;
  removeComponent: (id: string) => void;
  upsertSystemPanel: (panelId: string, panelType: SessionComponentType) => void;
  removeSystemPanel: (panelId: string) => void;
  clearSystemPanels: () => void;

  // Control actions
  setUiInterface: (uiInterface: UIInterface) => void;
  setPersistSession: (persist: boolean) => void;
  setEphemeral: (ephemeral: boolean) => void;

  // User mode actions (timeline workflow)
  setUserMode: (mode: 'developer' | 'client') => void;
  setStagedDeveloperMessage: (message: string | null) => void;

  // User messages history actions
  setUserMessagesHistory: (history: string[]) => void;
  appendToUserMessagesHistory: (message: string) => void;
  clearUserMessagesHistory: () => void;

  // Per-agent status actions
  setAgentStatus: (agentId: string, status: AgentStatus) => void;
  resetAllAgentStatuses: (status?: AgentStatus) => void;

  // Workflow status action for optimistic local transitions before the
  // canonical workflow_* session event arrives.
  setWorkflowStatus: (status: WorkflowStatus) => void;

  // State actions
  setError: (error: string | null) => void;
  clearError: () => void;
  setScrollToComponentId: (componentId: string | null) => void;
  clearScrollToComponentId: () => void;
  setPreserveScrollOnSessionChange: (preserve: boolean) => void;
  triggerSubmit: () => void;

  // Editing actions
  startEdit: (eventId: string, initialData: string | EditingData) => void;
  updateEditingData: (data: EditingData) => void;
  cancelEdit: () => void;

  // Branching UI state actions
  showBranches: (componentId: string) => void;
  hideBranches: () => void;
  scrollToComponent: (componentId: string) => void;

  // Translation actions
  setPreferredTranslationLanguage: (language: string | null) => void;
  cacheTranslation: (componentId: string, language: string, text: string) => void;
  setActiveTranslation: (componentId: string, language: string | null) => void;
  resetAllTranslations: () => void;
  setComponentTranslating: (componentId: string, translating: boolean) => void;

  // Pending library items actions
  addPendingLibraryItems: (ids: string[]) => void;
  removePendingLibraryItem: (id: string) => void;
  clearPendingLibraryItems: () => void;

  // Reset entire store
  reset: () => void;
}
