/**
 * Coherent conversation simulation for performance testing.
 * Scenario: Building a complex Task Management Dashboard from scratch.
 */
export const userPrompts: string[] = [
  "I want to build a task management dashboard using React and TypeScript.",
  "Let's use TailwindCSS for styling. Can you set up the initial project structure?",
  "Please create a Layout component with a sidebar and a top navigation bar.",
  "The sidebar should have links for Dashboard, My Tasks, Projects, and Settings.",
  "Now let's create the Dashboard view. It should have some summary cards at the top.",
  "Add a 'TaskCompletion' chart component using Recharts to the dashboard.",
  "I need a 'Recent Activity' feed component below the chart.",
  "Let's define the TypeScript interfaces for a Task and a User.",
  "Create a mock data generator for tasks so we can visualize the UI.",
  "Implement a TaskList component that displays tasks in a table format.",
  "Add sorting functionality to the TaskList table headers.",
  "We need a filter bar above the list to filter by status and priority.",
  "Make the status badges have different colors based on their value (todo, in-progress, done).",
  "Now, let's build a 'Create Task' modal form.",
  "Use react-hook-form for the form handling.",
  "Add validation to ensure the task title is at least 3 characters long.",
  "The modal should close when I click outside of it or press Escape.",
  "Let's add a 'Project' detail view. It should show project metadata and its associated tasks.",
  "Create a kanban board view for the tasks in the project detail page.",
  "I want to be able to drag and drop tasks between columns in the kanban board.",
  "We need to handle the drag end event to update the task status locally.",
  "Now let's add a dark mode toggle in the settings.",
  "Update the Tailwind config to support dark mode properly.",
  "The sidebar icons should change style when active.",
  "Let's add a user profile section in the top right of the navbar.",
  "Create a dropdown menu for the user profile with 'Profile', 'Settings', and 'Logout'.",
  "I want to add a 'Comments' section to the Task detail view.",
  "Create a Comment component that shows the user avatar, name, date, and text.",
  "Allow users to reply to comments (nested comments).",
  "Let's add file attachment support to tasks. Just the UI for now.",
  "Create a file upload dropzone component.",
  "Show the list of attached files with their file type icons.",
  "We need a search bar in the top navigation that searches across tasks and projects.",
  "Implement a debounce hook for the search input.",
  "Create a SearchResults dropdown that appears when typing.",
  "Let's refactor the state management to use Zustand.",
  "Create a useTaskStore to handle CRUD operations for tasks.",
  "Move the task filtering logic into the store selectors.",
  "Now let's add some unit tests for the TaskList component.",
  "Write a test to ensure the correct number of tasks are rendered.",
  "Write a test to check if the sorting function works correctly.",
  "I noticed a bug where the modal doesn't reset its state after closing. Can you fix it?",
  "The kanban board is flickering when dragging. Let's optimize the re-renders.",
  "Use React.memo for the KanbanColumn component.",
  "Let's add an 'Export to CSV' button for the task list.",
  "Implement the function to convert the task data to CSV format.",
  "Add a confirmation dialog before deleting a task.",
  "We need a loading skeleton state for the dashboard while data is fetching.",
  "Create a generic Skeleton component we can reuse.",
  "Finally, add some error boundary components to catch UI crashes."
];
